name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: download ndk
      run: wget -c https://dl.google.com/android/repository/android-ndk-r25c-linux.zip -o ./android-ndk-r25c-linux.zip
    - name : install fastjar
      run: sudo apt-get install fastjar
    - name : unzip
      run: jar xvf android-ndk-r25c-linux.zip
    - name: set path
      run: |
         sudo gedit ~/.bashrc
         export NDK=./android-ndk-r20b
         export PATH=${PATH}:$NDK
        
    
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'


    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        path: ./app/build/outputs/apk/release/*.apk
